live_config_reload = true

# theme example, commented out as it changes cursor color in vim as well
# which makes it too light for use with light color scheme
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"
dynamic_padding = true

[font]
size = 14.0

[font.bold]
family = "ZedMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ZedMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ZedMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "ZedMono Nerd Font"
style = "Light"
